#include <iostream>
#include "def.h"

int main()
{
	//RESERVED, SET AS REVIEW ONLY UNLESS SOMETHING APPEARS CHALLENGING OR UNKNOWN
	std::cout<<"RESERVED, SET AS REVIEW ONLY UNLESS SOMETHING APPEARS CHALLENGING OR UNKNOWN\n\n";
	
	return 0;
}
